ADD: SignUpView added
wecode-bootcamp-korea/18-1st-klush-backend pull request #2
Opened 2021-03-19 06:11 UTC by ziy0ung1234

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- models.py 생성.
		 
## 수정 사항들 자세한 내용

- 앱 4가지(user,product,order,review) 생성
- 각 앱마다 models.py 클래스 작성 후 관계 참조 확인.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-21 06:25 UTC, Kang-kyunghun requested changes

2021-03-21 06:25 UTC, Kang-kyunghun commented on user/views.py
> +                return JsonResponse({'message':' 이미 가입되어 있습니다.'}, status=400)
저희가 status 코드 이외에 message를 주는 이유는한글로 클라인트에게 설명하는것이 아니고 같은 status 코드에 여러 상황이 있기 때문에 그 상황을 프론트엔드에게 알려주기 위해서 입니다. 따라서 최소한으로 메시지를 전달하는 것이 좋습니다.

다른 return 메시지들도 확인해보고 수정해 주세요.
 
```suggestion
                return JsonResponse({'message' : 'DUPLICATED_INFORMATION'}, status=400)
```

2021-03-21 06:25 UTC, Kang-kyunghun commented on user/views.py
> +            decoded_password = password_crypt.decode('utf-8')
비밀번호 같은 경우 형식을 확인하고, 암호화 과정에 들어갑니다. 만약에, 비밀번호 암호를 끝내고, 이름이나 폰번호 확인 과정에서 회원가입이 완료가 되지 않으면 암호화 과정을 괜히 한 것이 됩니다. 
그래서, 비밀번호를 확인하는 과정을 가장 뒤로 보내는 것이 좋을 것 같습니다.

2021-03-21 06:25 UTC, Kang-kyunghun commented on user/views.py
> +            password         = data['password'].encode('utf-8')
password라는 변수가 위에서도 한 번 사용 되었는데, 중복으로 사용되는 느낌이 듭니다. 확인해 주세요.

2021-03-21 06:25 UTC, Kang-kyunghun commented on user/views.py
> +            User.objects.create(email=email, password=decoded_password, name=name, phone_number=phone_number, nickname=nickname)
가독성을 위해 아래와 같이 바꾸는 것을 추천 드립니다.
```suggestion
            User.objects.create(
                email        = email, 
                password     = decoded_password, 
                name         = name, 
                phone_number = phone_number, 
                nickname     = nickname
                )
```

2021-03-21 06:25 UTC, Kang-kyunghun commented on user/views.py
> +            return JsonResponse({'message':'회원가입 되었습니다.'}, status=201)
```suggestion
            return JsonResponse({'message' : 'SUCCESS'}, status=201)
```

2021-03-21 06:57 UTC, ziy0ung1234 commented on user/views.py
> +                return JsonResponse({'message':' 이미 가입되어 있습니다.'}, status=400)
넹 확인했습니다-! 전부 수정하겠습니다

2021-03-21 07:48 UTC, ziy0ung1234 commented on user/views.py
> +            decoded_password = password_crypt.decode('utf-8')
그렇네여 수정하겠습니다-!

2021-03-21 07:56 UTC, ziy0ung1234 commented on user/views.py
> +            password         = data['password'].encode('utf-8')
변수 네임 변경했고 나머지 변수들도 이름 통일성있게 변경했습니다-!

2021-03-21 07:58 UTC, ziy0ung1234 commented on user/views.py
> +            User.objects.create(email=email, password=decoded_password, name=name, phone_number=phone_number, nickname=nickname)
확실히 한눈에 보이니까 가독성이 좋아보이네요!

2021-03-21 07:59 UTC, ziy0ung1234 commented on user/views.py
> +            return JsonResponse({'message':'회원가입 되었습니다.'}, status=201)
변경완료-!

2021-03-22 01:50 UTC, Kang-kyunghun requested changes
통신 결과 이미지도 첨부해 주세요.

2021-03-22 01:50 UTC, Kang-kyunghun commented on user/views.py
> +            decoded_password  = bycrpted_password.decode('utf-8')
```suggestion
            bycrpted_password = bcrypt.hashpw(password.encode('utf-8') bcrypt.gensalt())
            decoded_password  = bycrpted_password.decode('utf-8')
```
data['password']가 위에서 password에 저장되어 있으므로 다시 한 번 저장할 필요는 없을 것 같습니다.

2021-03-22 01:50 UTC, Kang-kyunghun commented on user/views.py
> +                )
```suggestion
                email        = email,
                password     = decoded_password,
                name         = name,
                phone_number = phone_number,
                nickname     = nickname
                )
```
가독성을 위해 한 줄이 아닌, 아래로 내려 썼을 경우에는 =을 기준으로 라인 맞춰주세요

2021-03-22 05:41 UTC, ziy0ung1234 commented
![Uploading 스크린샷 2021-03-22 오후 2.41.30.png…]()

2021-03-22 08:57 UTC, Kang-kyunghun commented
LGTM~~!!!!

2021-03-22 08:57 UTC, merged