[18기 한지영] ADD: SignInView and decorator
wecode-bootcamp-korea/18-1st-klush-backend pull request #4
Opened 2021-03-19 12:27 UTC by ziy0ung1234

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- signin views 생성
- utils folder 새로 생성후 decorator  
## 수정 사항들 자세한 내용
### SignInView
- signup과 마찬가지로 이메일과 패스워드 정규식 확인 
- 유저가 인풋값으로 보낸 이메일과 이미 가입된 이메일을 비교해 맞다면 비밀번호 check
- 둘다 맞다면 로그인 성공 메세지와 status code 200리턴
### Decorator
- request.headers안에 있는 authotization에서 토큰을 꺼냄
- 꺼낸 토큰을 decode 한후 토큰의 user_id정보를 리퀘스트에 같이보냄
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-21 06:39 UTC, Kang-kyunghun requested changes

2021-03-21 06:39 UTC, Kang-kyunghun commented on user/views.py
> +import json, re
```suggestion
import json
Import re
```

2021-03-21 06:39 UTC, Kang-kyunghun commented on user/views.py
> +from my_settings import SECRET_KEY, ALGORITHM
import 라인 맞춰주세요.

2021-03-21 06:39 UTC, Kang-kyunghun commented on user/views.py
> +
불필요한 공백 제거해 주세요.

2021-03-21 06:39 UTC, Kang-kyunghun commented on utils/decorator.py
> +            request.user = User.objects.get(id=decoded_token["user_id"])
```suggestion
            token         = request.headers['Authorization']
            decoded_token = jwt.decode(token, SECRET_KEY, ALGORITHM)
            request.user  = User.objects.get(id=decoded_token["user_id"])
```

2021-03-21 06:39 UTC, Kang-kyunghun commented on utils/decorator.py
> +            return JsonResponse({'message':'It returned None instead.'}, status=400)
해당 에러는 어느 상황에서 발생하는 에러인가요?(질문)

2021-03-21 06:39 UTC, Kang-kyunghun commented on utils/decorator.py
> +            return JsonResponse({'message': 'Not exact token'}, status=400)
```suggestion
            return JsonResponse({'message' : 'INVALID_TOKEN'}, status=?)
```
status code를 400을 사용 했는데, 400말고 현재 상황에서 어떠한 status 코드를 사용 할 수 있을까요?

2021-03-21 06:39 UTC, Kang-kyunghun commented on user/views.py
> +            return JsonResponse({'message':'INVALID_USER'}, status=401)
exception 꼼꼼히 잘 잡아주셨습니다 👍  exception으로 에러 핸들링 하는 방법도 좋지만,  `DoesNotExist` 가 발생할 수 있는 로직에서 `if` 조건문으로 먼저 데이터 존재 여부를 따져보는 것이 좋습니다. 

exception처리를 할 경우 코드를 눈으로 읽으면서 천천히 내려오다가 언제 어느 시점에 에러 핸들링을 하는지 알 기가 어렵습니다 (exception이 모두 제일 아래에 있기 때문에 가독성이 떨어진다고 표현할 수 있습니다.)

이러한 이유로 로직상에서 잡을 수 있는 에러는 모두 잡고, 정말 어쩔 수 없는 경우에 exception 처리를 해주는 것이 좋습니다.

2021-03-21 06:39 UTC, Kang-kyunghun commented on user/views.py
> +                return JsonResponse({'message':'유효하지 않은 비밀번호 입니다.'}, status=401)
'사용자가 존재하지 않을 때' 와 '존재는 하지만 비밀번호는 틀렸을 때'를 구분하여 에러메세지를 전달하면, 보안에 취약할 수 있습니다. 제3자가 이메일을 알아내어, 비밀번호만 계속 바꿔가며 해킹을 시도할 때에 힌트를 주는 격이 됩니다 🙂  따라서, 보다 안전한 서비스를 만들기 위하여 두 경우의 에러메세지와 에러 코드를 통일시키는 것을 추천드립니다.

2021-03-21 06:46 UTC, ziy0ung1234 commented on user/views.py
> +import json, re
확인했습니다-!

2021-03-21 06:48 UTC, ziy0ung1234 commented on user/views.py
> +from my_settings import SECRET_KEY, ALGORITHM
확인!import라인 줄지어놨습니다-!

2021-03-21 08:29 UTC, ziy0ung1234 commented on utils/decorator.py
> +            return JsonResponse({'message':'It returned None instead.'}, status=400)
아 이거 댓글작성하는 뷰짜고 공부하면서 확인하다 나온건데 저는 거기서 나오는 에러 다 except로 핸들링해야하는줄 알고 작성했다 value error는 핸들링하는거 아니라고 해서 빼야했는데 못뺐습니다8_8

2021-03-21 08:29 UTC, ziy0ung1234 commented on user/views.py
> +
넵 확인했습니다-!

2021-03-21 08:31 UTC, ziy0ung1234 commented on utils/decorator.py
> +            request.user = User.objects.get(id=decoded_token["user_id"])
확인했습니다-!

2021-03-21 08:37 UTC, ziy0ung1234 commented on user/views.py
> +                return JsonResponse({'message':'유효하지 않은 비밀번호 입니다.'}, status=401)
'INVALID_PASSWORD' 메세지로 통일했고 status code 는 비인증의 상태이기 때문에 401로 맞췄습니다.  또한 email역시 비인증상태이기 때문에 401로 변경했습니다!

2021-03-21 08:42 UTC, ziy0ung1234 commented on utils/decorator.py
> +            return JsonResponse({'message': 'Not exact token'}, status=400)
`401 Unauthorized`가 맞는거 같습니다!

토큰이 유효하지 않다는 것은 토큰에 담겨있는 유저 정보도 유효하지 않다고 생각했고, 즉 비인증 상태를 의미한다고 생각해서 401로 수정하였습니다

2021-03-21 09:54 UTC, ziy0ung1234 commented on user/views.py
> +            return JsonResponse({'message':'INVALID_USER'}, status=401)
경훈님 if문으로 DoesNotExist 로직을 잡아주었는데 그럼 except User.DoesNotExist 는 굳이 잡을 필요가 없는 부분인게 맞죠?

2021-03-22 01:58 UTC, Kang-kyunghun requested changes

2021-03-22 01:58 UTC, Kang-kyunghun commented on utils/decorator.py
> +            return JsonResponse({'message': 'Not exact token'}, status=401)
```suggestion
            return JsonResponse({'message': 'INVALID_TOKEN'}, status=401)
```
INVALID_TOKEN이 더 어울릴 것 같습니다.

2021-03-22 01:58 UTC, Kang-kyunghun commented on user/views.py
> +            access_token = jwt.encode({'user_id': user.id}, SECRET_KEY, ALGORITHM)
1. user을 filter을 사용해서 존재 여부를 확인 하려고 한 점 매우 잘 했습니다.
2. 그런데 애초에 user가 존재하지 않으면, 위의 if문들을 통과할 필요가 없겠죠? 에러가 처리가 되는 순서에 따라 어떤 점이 더 효율적일까 한 번 생각해 보세요.
3. filter로 user 정보를 잘 가져왔을 때 user.id가 잘 나오셨나요? queryset을 가져오는 method와 instance을 가져오는 method의 차이를 한 번 생각해 보세요.

2021-03-22 01:58 UTC, Kang-kyunghun commented on user/views.py
> +            return JsonResponse({'token': access_token, 'name': user.name, 'message':'SUCCESS'}, status=200)
user의 name을 응답 값에 같이 보내주는 이유가 따로 있나요?

2021-03-22 02:20 UTC, ziy0ung1234 commented on user/views.py
> +            return JsonResponse({'token': access_token, 'name': user.name, 'message':'SUCCESS'}, status=200)
그냥..제가 보고싶어서,,

2021-03-22 03:56 UTC, ziy0ung1234 commented
<img width="1152" alt="스크린샷 2021-03-22 오후 12 55 43" src="https://user-images.githubusercontent.com/77558556/111938767-08e59a00-8b0e-11eb-8523-9dffaca237ab.png">

2021-03-22 09:06 UTC, merged

2021-03-22 09:06 UTC, Kang-kyunghun commented
LGTM~~!!!