[18기 최인아] ADD ProductList views.py, urls.py
wecode-bootcamp-korea/18-1st-klush-backend pull request #7
Opened 2021-03-23 07:03 UTC by InahChoi

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- ProductList views.py, urls.py  작성
		 
## 수정 사항들 자세한 내용
- Product list 브랜치 생성하여 views, urls 작성

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-23 07:16 UTC, InahChoi commented
<img width="902" alt="api_product_list" src="https://user-images.githubusercontent.com/52025291/112108071-17f24800-8bf3-11eb-959a-4207f89a03ee.png">

2021-03-23 07:42 UTC, Kang-kyunghun requested changes

2021-03-23 07:42 UTC, Kang-kyunghun commented on product/views.py
> +            return JsonResponse({'Message':'DOES_NOT_EXIST'}, status = 401)
해당 예외처리를 사용한 이유가 무엇인가요?

2021-03-23 07:42 UTC, Kang-kyunghun commented on product/views.py
> +                    'product_label'  : product.label.name,
label이 MtoM으로 알고 있는데, 라벨이 여러개 있을 경우에도 잘 나오나요? 확인해 주세요.

2021-03-23 07:42 UTC, Kang-kyunghun commented on product/views.py
> +                product_list.append(dict)
for문으로 list 잘 만드셨습니다.
그런데, 일반 for문 보다는 list comprehension을 사용하는 것이 효율면에서 더 좋은 방법입니다. list comprehension으로 바꿔 주세요~

2021-03-23 07:45 UTC, Kang-kyunghun requested changes

2021-03-23 07:45 UTC, Kang-kyunghun commented on product/urls.py
> +    path('/product-list', ProductListView.as_view()),
다음과 같이 urlpattern을 설정하면 product list를 보내주는 API의 urlpattern이 product/product-list가 됩니다.
```suggestion
    path('', ProductListView.as_view()),
```
위와 같이 수정하면 /product 만으로도 제품들의 정보를 받아 올 수 있고 더 RESTfull해 집니다.

2021-03-23 14:19 UTC, InahChoi commented on product/views.py
> +                    'product_label'  : product.label.name,
라벨 수정 중입니당

2021-03-23 14:20 UTC, InahChoi commented on product/views.py
> +                product_list.append(dict)
알게씀당💡

2021-03-23 14:22 UTC, InahChoi commented on product/urls.py
> +    path('/product-list', ProductListView.as_view()),
감사합니당 경훈님💡

2021-03-24 04:24 UTC, InahChoi commented on product/views.py
> +            return JsonResponse({'Message':'DOES_NOT_EXIST'}, status = 401)
`get` 사용할 때 예외처리 해야 하는 거 아니에여? 그래서 넣었는데
다시 생각해보니 그 `get`이 아니였읍니다..

경훈님 언제오시죠 지금 1시 24분이에요

2021-03-24 07:51 UTC, InahChoi commented
![스크린샷 2021-03-24 오후 4 51 16](https://user-images.githubusercontent.com/52025291/112273858-2e66d500-8cc1-11eb-840d-db3eeab08065.png)

2021-03-24 09:40 UTC, Kang-kyunghun commented
LGTM

2021-03-24 09:41 UTC, merged