[18기 최인아] ADD: product_detail views, urls
wecode-bootcamp-korea/18-1st-klush-backend pull request #8
Opened 2021-03-23 07:12 UTC by InahChoi

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- ADD: product_detail views, urls
		 
## 수정 사항들 자세한 내용
- feature/product-detail 브랜치를 새로 생성하여 ADD: product_detail views, urls 작성

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-23 07:13 UTC, InahChoi commented
<img width="902" alt="get_product_detail" src="https://user-images.githubusercontent.com/52025291/112107764-b631de00-8bf2-11eb-8184-501a0b827ece.png">

2021-03-23 07:49 UTC, Kang-kyunghun requested changes

2021-03-23 07:49 UTC, Kang-kyunghun commented on product/urls.py
> +    path('/product-detail/<int:product_id>', ProductDetailView.as_view()),
다음과 같이 urlpattern을 설정하면 product detail를 보내주는 API의 urlpattern이 product/product-detail/<product_id>가 됩니다.
```suggestion
    path('/<int:product_id>', ProductDetailView.as_view()),
```
위와 같이 수정하면 /product/<product_id> 만으로도 제품들의 정보를 받아 올 수 있고 더 RESTfull해 집니다.

2021-03-23 07:49 UTC, Kang-kyunghun commented on product/views.py
> +            product        = Product.objects.get(id = product_id)
produt_id가 db에 없는 데이터가 들어오게 되면 objects.get을 할 때 에러가 발생하게 됩니다. 이런 상황에 대해 if를 이용하여 예외처리 해주세요.

2021-03-24 07:45 UTC, InahChoi commented
![스크린샷 2021-03-24 오후 4 45 15](https://user-images.githubusercontent.com/52025291/112273133-5a358b00-8cc0-11eb-8c8a-6b2f2fe7a8f4.png)
![스크린샷 2021-03-24 오후 4 44 48](https://user-images.githubusercontent.com/52025291/112273147-5d307b80-8cc0-11eb-87df-7c38e151442e.png)
![스크린샷 2021-03-24 오후 4 45 06](https://user-images.githubusercontent.com/52025291/112273150-5dc91200-8cc0-11eb-9399-06e2f876f2a1.png)

2021-03-24 09:26 UTC, Kang-kyunghun commented
LGTM

2021-03-24 09:26 UTC, merged